AllCops:
  Exclude:
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'config/application.rb'
    - 'config/environments/*'
    - 'config/deploy.rb'
    - 'config/deploy/*'
    - 'coverage/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'public/**/*'
    - 'vendor/**/*'
    - 'bin/*'
    - 'script/*'

require:
  - rubocop-rails
  - rubocop-performance

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  CountComments: true
  Max: 25
  ExcludedMethods: []
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/migrate/*.rb'

Metrics/MethodLength:
  Max: 15

Layout/LineLength:
  Description: 'Limit lines to 120 characters.'
  Max: 120

Lint/Loop:
  Enabled: false